# Swagger UI / OpenAPI Configuration
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.packages-to-scan=desafio.dio.design_patterns.controller
springdoc.swagger-ui.tryItOutEnabled=true
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.filter=true
springdoc.swagger-ui.defaultModelsExpandDepth=1
springdoc.swagger-ui.defaultModelExpandDepth=1
springdoc.swagger-ui.displayRequestDuration=true
springdoc.group-configs[0].group=design-patterns
springdoc.group-configs[0].paths-to-match=/clientes/**

# Application Name
spring.application.name=Desafio Dio Design Patterns
